name: Run UI test suite (Cypress)

on:
  pull_request:
    branches:
      - main  
    types:
      - labeled
      - opened
      - reopened
      - synchronize



jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 16.x

      - name: install deps
        run: |
          npm install

      - name: run the app
        run: |
          npm run dev &

      - name: Run the cypress tests
        uses: cypress-io/github-action@d79d2d530a66e641eb4a5f227e13bc985c60b964 # v4.2.2
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        with:
          record: false
          config: video=false,screenshotOnRunFailure=false
          build: npx cypress info
          spec: |
            cypress/e2e/frontend.cy.js
