name: Run UI test suite (Cypress)

on:
  pull_request:
    branches:
      - main  
    types:
      - labeled
      - opened
      - reopened
      - synchronize



jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 16.x

      - name: install deps
        run: |
          npm install

      - name: run the app
        run: |
          npm run dev &

      - name: Run the cypress tests
        uses: cypress-io/github-action@d79d2d530a66e641eb4a5f227e13bc985c60b964 # v4.2.2
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        with:
          record: false
          config: video=false,screenshotOnRunFailure=false
          build: npx cypress info
          spec: |
            cypress/e2e/frontend.cy.js
