name: Copy files to Production S3 bucket

on:
  workflow_dispatch:
  push:
    tags:
      - v[1234].[0-0]+.[0-9]+

permissions:
  id-token: write
  contents: write

env:
  PRODUCTION_ACCOUNT_ID: "296255494825"

jobs:
  s3-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1

      - name: Get latest tag
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@385a2a0b6abf6c2efeb95adfac83d96d6f968e0c" # v1.3.0

      - name: Get S3 bucket tag
        shell: bash
        run: |
          echo "BUCKET_TAG=$(aws s3api get-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --query TagSet[?Key == 'Version'].Value | [0])" >> $GITHUB_ENV

      - name: Seed S3 bucket tag
        if: ${{ env.BUCKET_TAG }} == "" or ${{ env.BUCKET_TAG }} == "[]"
        shell: bash
        run: |
          aws s3api put-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --tagging 'TagSet=[{Key=Version, Value=v1.0.0}]'
          echo "BUCKET_TAG=v1.0.0" >> $GITHUB_ENV

      - name: Generate Tailwind CSS file
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          npm install
          npm run build

      - name: Upload to S3 bucket
        if: ${{ steps.latest-tag.outputs.tag }} != ${{ env.BUCKET_TAG }}
        run: |
          cd ./dist
          aws s3 sync . s3://${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }}

      - name: Update S3 bucket Tag
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          aws s3api put-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --tagging 'TagSet=[{Key=Version, Value=${{ steps.latest-tag.outputs.tag }} }]'

      - name: Invalidate CloudFront cache
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PRODUCTION_SYSTEM_STATUS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json='{"text":"System Status Frontend upload to Production failed <https://github.com/${{ github.repository }}>!"}'
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_NOTIFY_DEV_WEDBOOK }}
