name: Copy files to Production S3 bucket

on:
  workflow_dispatch:
  push:
    tags:
      - v[1234].[0-0]+.[0-9]+

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  PRODUCTION_ACCOUNT_ID: "296255494825"
  ACCOUNT_ID: ${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ca-central-1

jobs:
  s3-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14"

      - name: Configure credentials to Notify using OIDC
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/notification-system-status-frontend-prod-upload-to-s3
          role-session-name: NotifySystemStatusFrontendApply
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get latest tag
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce" # v1.4.0

      - name: Get S3 bucket tag
        shell: bash
        run: |
          echo "BUCKET_TAG=$(aws s3api get-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --query \"TagSet[?Key=='Version'].Value | [0]\" --output text 2>/dev/null || true)" >> "$GITHUB_ENV"

      - name: Seed S3 bucket tag
        if: ${{ env.BUCKET_TAG }} == "" or ${{ env.BUCKET_TAG }} == "[]"
        shell: bash
        run: |
          aws s3api put-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --tagging 'TagSet=[{Key=Version, Value=v1.0.0}]'
          echo "BUCKET_TAG=v1.0.0" >> $GITHUB_ENV

      - name: Generate Tailwind CSS file
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          npm install
          npm run build

      - name: Upload to S3 bucket
        if: ${{ steps.latest-tag.outputs.tag }} != ${{ env.BUCKET_TAG }}
        run: |
          cd ./dist
          aws s3 sync . s3://${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }}

      - name: Update S3 bucket Tag
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          aws s3api put-bucket-tagging --bucket ${{ secrets.PRODUCTION_SYSTEM_STATUS_BUCKET }} --tagging 'TagSet=[{Key=Version, Value=${{ steps.latest-tag.outputs.tag }} }]'

      - name: Invalidate CloudFront cache
        if: steps.latest-tag.outputs.tag != ${{ env.BUCKET_TAG }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PRODUCTION_SYSTEM_STATUS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json='{"text":"System Status Frontend upload to Production failed <https://github.com/${{ github.repository }}>!"}'
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_NOTIFY_DEV_WEBHOOK }}
