name: Copy files to Staging S3 bucket

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  STAGING_ACCOUNT_ID: "239043911459"

jobs:
  s3-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14"

      - name: Generate Tailwind CSS file
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1

      - name: Upload to S3 bucket
        run: |
          cd ./dist
          aws s3 sync . s3://${{ secrets.STAGING_SYSTEM_STATUS_BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_SYSTEM_STATUS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json='{"text":"System Status Frontend upload to Staging failed <https://github.com/${{ github.repository }}>!"}'
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_NOTIFY_DEV_WEDBOOK }}
