name: Copy files to S3 bucket

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  STAGING_ACCOUNT_ID: "239043911459"
  PRODUCTION_ACCOUNT_ID: "296255494825"


jobs:

  s3-backup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Generate Tailwind CSS file
      run: |
        npm install
        npm run build
        pwd
        mv ./dist/css/index.css src/index.css

    # Staging upload
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_KEY_ID }}
        aws-region: ca-central-1

    - name: Upload to S3 bucket
      run: |
        cd src
        aws s3 sync . s3://${{ secrets.STAGING_SYSTEM_STATUS_BUCKET }}
    # - name: Notify Slack channel if this job failed
    #   if: ${{ failure() }}
    #   run: |
    #     json='{"text":"System Status Frontend failed to upload <https://github.com/${{ github.repository }}>!"}'
    #     curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_NOTIFY_WEBHOOK }}
